### ISSUE TITLE
Periodic console spam

### ISSUE THREAD

**Issue by sblectric** [oitsjustjose/Persistent-Bits#8]
` A TileEntity type com.oitsjustjose.persistent_bits.tileentity.TileChunkLoader has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
        at com.oitsjustjose.persistent_bits.tileentity.TileChunkLoader.func_189515_b(TileChunkLoader.java:170) ~[TileChunkLoader.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:384) [atj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1012) [ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
`

This periodically spits out in my server's log, the loaders seem to be working, though.

**Comment by oitsjustjose** [comment]
What version of Persistent Bits are you using? I had this issue long ago but it's since been fixed (I hope..).

**Comment by sblectric** [comment]
This is Persistent Bits 1.0.5 on MC 1.10.2, Forge version 12.18.2.2121

**Comment by oitsjustjose** [comment]
Looked into the problem Pushing a solution in a few seconds - makes sense why they still work; the data that's failing to save is non-essential to their functionality 😄

**Comment by oitsjustjose** [comment]
New build (1.0.6) coming up on CurseForge shortly :)

**Comment by sblectric** [comment]
Thanks for the quick fix!
